### PR TITLE
Fix for link navigation

### LINKED ISSUE #378: Message's link navigation broken
Just click a link to Task in any message

### PR DESCRIPTION
**Pull request by haiodo**
Closes #378

Signed-off-by: Andrey Sobolev <haiodo@gmail.com>

### CODE REVIEW

File: plugins/platform-ui/src/components/internal/Root.svelte [hunk 1]
```diff
@@ -53,7 +53,7 @@
         currentAppErr = `There is no application route defined for ${appRoute}`
       }
     },
-    { application: '#default' }
+    { application: platform.getMetadata(routeMeta(defaultApp))?.route || '#default' }
```
Comment (sumboid) [inline plugins/platform-ui/src/components/internal/Root.svelte:56]: Is it possible that route would be empty string? In such case `??` would be more suitable

**Review by sumboid — APPROVED** [review]

**Review by z2sx — APPROVED** [review]
